# Name of the workflow
name: Run Selenium Tests

# When to run it
on:
  push:
    branches:
      - main  # Run when code is pushed to the main branch

# What to do
jobs:
  run_tests:
    runs-on: ubuntu-latest  # Use a fresh Ubuntu computer in the cloud
    steps:
      - name: Get my code
        uses: actions/checkout@v4  # Downloads your code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Use Python 3.9

      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Install Selenium, pytest, etc.

      - name: Run tests
        run: pytest  # Run your Selenium tests
